marzneshin/marzneshin

- app/dashboard/src/components/ServiceDialog/FormSchema.ts
- app/dashboard/src/components/ServiceDialog/index.tsx
- app/dashboard/src/contexts/DashboardContext.tsx
- app/dashboard/src/types/Service.ts
- chore: remove empty file
- fix: type conflict for service creation and editing
> fix: build failure for CI becuase type conflict for service creation and editing

- app/dashboard/src/components/ServiceDialog/index.tsx
> chore: remove debugging state viewer for react form plugin

- app/dashboard/src/components/Sidebar/index.tsx
- fix: dark mode compatibility for sidebar
- fix: less space between sidebar items
- #20
> fix: Sidebar dark mode

- app/dashboard/src/App.tsx
- app/dashboard/src/contexts/AdminContext.tsx
- app/dashboard/src/pages/Login.tsx
- feat(auth): new context state for managing the authentication state of loggined admin
- feat(auth): use the new admin state for managing protect route
- #24
> fix: auto navigation to login page

- app/db/crud.py
- app/jobs/record_usages.py
- app/jobs/reset_user_data_usage.py
- app/jobs/review_users.py
- app/marznode/grpc.py
- app/marznode/marznode.proto
- app/marznode/marznode_pb2.py
- app/utils/notification.py
- app/views/user.py
User statistics is functional again by fetching the stats from nodes
includes fixes to user reviewal for datalimit/expiry and periodical reset
> fix: user usages are fetched and stored in the database

- app/db/crud.py
- app/db/migrations/versions/20faa9f18c0a_init.py
- app/db/models.py
- app/marznode/operations.py
- app/models/user.py
- app/utils/jwt.py
- app/utils/notification.py
- app/views/subscription.py
- app/views/user.py
This fixes revoking subscription and also improves subscription url format by using users' usernames and keys in the url.
> feat: better subscription links

- app/db/migrations/versions/20faa9f18c0a_init.py
- app/db/models.py
- app/models/user.py
- remove duplicate indexes on primary key columns
- case collations where replaced with string constraints in pydantic models to ensure compatibility with postgresql
> refactor: better database structure

- app/marznode/operations.py
- app/models/admin.py
- app/models/user.py
- app/routes/service.py
- app/routes/user.py
- app/tasks/reset_user_data_usage.py
> Fix: user and service modification

- .github/workflows/api-ci.yml
- .github/workflows/api-codeql.yml
- .github/workflows/dashboard-codeql.yml
- improv: prevent word splitting
- improv: CI separation of workflows for different areas of the app
> improve: separate codeql runnner for API and Dashboard

- .github/workflows/package.yml
- Dockerfile
- makefile
- requirements.txt
- add psycopg for postgres
- add Dockerhub for pushing
- remove unneeded dependencies to reduce image size
> fix: docker containarization

- .github/workflows/release.yml
- Dockerfile
- feat: use release-please
- fix: removing stages for docker build
> ci: release-please container-fix v0.1.4

- app/dashboard/package-lock.json
- app/dashboard/package.json
- app/dashboard/src/index.tsx
- app/dashboard/src/pages/home/statistics.tsx
- app/dashboard/src/pages/hosts/container.tsx
- app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx
- app/dashboard/src/pages/hosts/table/index.tsx
- app/dashboard/src/pages/nodes/modals/core-settings-modal.tsx
- app/dashboard/src/pages/nodes/table/index.tsx
- app/dashboard/src/pages/services/dialog/index.tsx
- app/dashboard/src/pages/services/table.tsx
- app/dashboard/src/pages/users/dialog/index.tsx
- app/dashboard/src/pages/users/table/index.tsx
- app/dashboard/src/service/react-query.ts
- app/dashboard/src/stores/inbounds.store.ts
- app/dashboard/src/stores/nodes.store.ts
- app/dashboard/src/stores/services.store.ts
- app/dashboard/src/stores/users.store.ts
- makefile
- fix: migrate to @tanstack/react-query v5
- fix: hosts table correct query invalidation
- build: preview and install deps
> fix: migrate tanstack query v5 hosts table

- app/dashboard/public/locales/en.json
- app/dashboard/src/components/table/empty-section.tsx
- app/dashboard/src/pages/home/statistics.tsx
- app/dashboard/src/pages/hosts/filters.tsx
- app/dashboard/src/pages/hosts/table/index.tsx
- app/dashboard/src/stores/inbounds.store.ts
- fix: avoid undefined inbounds while fetching hosts
- fix: render when it's effected
> fix: undefined request arg, statistics rerender

- app/dashboard/package-lock.json
- app/dashboard/src/pages/hosts/container.tsx
- app/dashboard/src/pages/hosts/dialog/default-values.ts
- app/dashboard/src/pages/hosts/dialog/index.tsx
- app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx
- app/dashboard/src/pages/hosts/table/index.tsx
- app/dashboard/src/stores/inbounds.store.ts
This PR aims to resolve the crash while opening and interacting with hosts dialog due to memory leak of the Re-sizable Panel library.
> fix: hosts dialog crash

- app/db/migrations/versions/20faa9f18c0a_init.py
- docker-compose.yml
- script.sh
deploy marznode alongside marzneshin
> feat: Painless deployment

- app/marzneshin.py
- app/models/node.py
- app/models/user.py
- app/routes/admin.py
- app/routes/inbounds.py
- app/routes/node.py
- app/routes/service.py
- app/routes/system.py
- app/routes/user.py
paginate resources (including users, admins, nodes, inbounds, hosts) using fastapi-pagination
> feat: api pagination

- .github/workflows/dashboard-ci.yml
- dashboard/.eslintrc.cjs
- dashboard/package.json
- dashboard/pnpm-lock.yaml
- dashboard/src/app.tsx
- dashboard/src/features/i18n/index.ts
- dashboard/tsconfig.json
- dashboard/vite.config.ts
- **fix: vite config and lintg**
- **ci: ci for the new UI rewrite**
- **fix: linting rules**
- #161
> ci: adapt new ui rewrite

- dashboard/src/features/auth/login/form.tsx
- Eliminate placeholders
- Annotating the type of each field for better user interaction and browser default value suggestion
> improve(login-form): refine username and password fields

- dashboard/src/features/nodes/dialogs/mutation.dialog.tsx
- dashboard/src/features/sidebar/sidebar.tsx
- Disable submit button during operations to prevent multiple submissions.
- Enhance sidebar-item appearance for a sleeker look.
- Correct alignment of "add as new hosts" field for better layout consistency.
- Reorganize mutation dialog fields for improved clarity and usability.
> fix: minor UI dialog bug 

- dashboard/src/app.tsx
- dashboard/src/components/nav-dir/index.tsx
- **fix: using hash history based roting**
- **improve: capitalizing nav-dir items**
> fix(routing): usingg hash history based routing

- dashboard/src/components/entity-table/entity-table-provider.ts
- dashboard/src/components/entity-table/hooks/use-entity-query.ts
- dashboard/src/components/entity-table/hooks/use-entity-table.ts
- dashboard/src/components/entity-table/hooks/use-filtering.ts
- dashboard/src/components/entity-table/index.tsx
- dashboard/src/components/entity-table/table-filtering.tsx
- dashboard/src/components/entity-table/table.tsx
- dashboard/src/features/nodes/services/nodes.query.ts
- dashboard/src/features/services/services/services.query.ts
- dashboard/src/features/users/services/users.query.ts
> feat(entity-table): server side filtration entity table

- dashboard/src/components/header/index.tsx
- dashboard/src/components/nav-dir/index.tsx
- dashboard/src/features/auth/auth.store.ts
- dashboard/src/features/auth/index.ts
- dashboard/src/features/auth/logout/index.tsx
- dashboard/src/features/language-switch/index.tsx
- dashboard/src/routes/_auth/login.tsx
- dashboard/src/routes/_dashboard.tsx
- dashboard/src/utils/fetch.ts
- **chore: remove dead code**
- **feat: reset the token when login page is opened**
- **feat: logged in state**
- **feat: redirect to login page if the user is not loggedin**
> fix(login-reftesh-invalidation): invalidate token only when user visted login page

- dashboard/src/features/users/dialogs/mutation/fields/services.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
> fix(users-mutation): services field corrupt data population while selecting services

- dashboard/src/components/entity-table/hooks/use-entity-query.ts
- dashboard/src/components/entity-table/hooks/use-entity-table.ts
- dashboard/src/components/entity-table/index.tsx
- dashboard/src/features/users/services/users.query.ts
- dashboard/src/features/users/tables/users/index.tsx
- **feat(entity-table): manual server side sort**
- **feat(users): server side sorted users fetching**
> feat(users-table-sort): server side sorting for users table

- dashboard/public/locales/kur.json
- dashboard/src/features/users/components/services-card.tsx
- dashboard/src/features/users/dialogs/mutation/fields/data-limit-reset-strategy.tsx
- dashboard/src/features/users/dialogs/mutation/fields/services.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
- Set the default expiration method tab accordingly to the user previous settings and existing settings
- Services get unregistered
> fix: services select undefined

- dashboard/src/components/entity-table/table.tsx
- dashboard/src/features/hosts/tables/inbound-hosts/index.tsx
- dashboard/src/features/hosts/tables/inbound-hosts/table.tsx
> improve(fetching): loader indicator while fetching query

- dashboard/package.json
- dashboard/pnpm-lock.yaml
- dashboard/src/features/users/components/used-user-traffic.tsx
> feat(users): pretty byte is shown in kibibyte format

- app/db/migrations/versions/20faa9f18c0a_init.py
- app/db/models.py
> improv: increase host and sni size to 1024

- dashboard/src/features/nodes/dialogs/settings/index.tsx
- dashboard/src/features/nodes/log/container.tsx
> fix(nodes-log): node settings messes up when xray logs are too long

- dashboard/public/locales/en.json
- dashboard/src/components/copy-button/index.tsx
- dashboard/src/components/stacks/horizontal.tsx
- dashboard/src/features/users/dialogs/settings/index.tsx
- dashboard/src/features/users/dialogs/settings/user-info/qrcode.tsx
- dashboard/src/features/users/dialogs/settings/user-info/subcription-link-button.tsx
- dashboard/src/features/users/dialogs/settings/user-info/subscription-actions.tsx
- dashboard/src/features/users/dialogs/settings/user-info/table.tsx
> fix: user sheet isn't looking good on small screens

- dashboard/src/components/stacks/vertical.tsx
- dashboard/src/features/services/dialogs/mutation.dialog.tsx
- dashboard/src/features/users/dialogs/mutation/fields/services.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
> fix(users-dialog): user creation dialog not responsive

- dashboard/src/features/hosts/dialogs/mutation/fields/fragment.tsx
- dashboard/src/features/hosts/dialogs/mutation/index.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
Dialog is made scrollable so in small height screen user can scroll to reach the submit button.
Closes #299
> fix(hosts-mutation-dialog): create/edit host dialog isn't responsive 

- .github/workflows/package.yml
This reverts commit 30f7a6b7ad61127aa743ac9b89b7c055084cf193.
> Revert "fix: provide write all permission (#306)"

- dashboard/src/components/entity-table/hooks/use-entity-table.ts
- dashboard/src/components/entity-table/table-pagination.tsx
> fix: users pagination initial state must be 1

- dashboard/src/components/entity-table/hooks/use-entity-table.ts
- dashboard/src/components/entity-table/table-pagination.tsx
Reverts khodedawsh/marzneshin#304
> Revert "fix: users pagination initial state must be 1"

- app/routes/subscription.py
- app/utils/keygen.py
- app/utils/share.py
- requirements.txt
> refactor: simplify subscription codebase

- .gitignore
- dashboard/src/features/users/components/used-user-traffic.tsx
- dashboard/src/features/users/dialogs/mutation/fields/data-limit.tsx
- dashboard/src/features/users/dialogs/mutation/fields/onhold-expire-duration.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
- dashboard/src/features/users/dialogs/mutation/sections/data-limit.tsx
- dashboard/src/features/users/dialogs/mutation/sections/expiration-method.tsx
- dashboard/src/features/users/dialogs/mutation/sections/use-expiration-method-tabs.ts
- dashboard/src/features/users/types/index.ts
> fix(user-editing): avoid forced value set while editing user for expiration method and datalimit field

- dashboard/src/features/hosts/dialogs/mutation/index.tsx
> fix(hosts-create): creating new host when previously cached values 

- dashboard/public/locales/en.json
- dashboard/src/features/hosts/dialogs/mutation/index.tsx
- dashboard/src/features/hosts/dialogs/settings/index.tsx
- dashboard/src/features/hosts/tables/inbound-hosts/columns.tsx
> fix(hosts-edit): set the port to null when its empty string

- app/db/migrations/versions/058eb11c5b17_user_reset_in_table.py
- app/db/models.py
lifetime_used_traffic shouldn't be null; should be 0 and also not nullable
> fix: mistake in the last migration

- app/db/crud.py
- app/db/models.py
- app/models/node.py
- app/models/proxy.py
- app/models/service.py
- app/models/user.py
- app/routes/service.py
- app/routes/subscription.py
- app/routes/user.py
- app/utils/share.py
- dashboard/src/components/entity-field-card/index.tsx
- dashboard/src/components/index.ts
- dashboard/src/features/services/dialogs/mutation/fields/inbounds.tsx
- dashboard/src/features/services/dialogs/mutation/index.tsx
- dashboard/src/features/services/services/service-inbounds.query.ts
- dashboard/src/features/services/services/services.query.ts
- dashboard/src/features/services/tables/inbounds/index.tsx
- dashboard/src/features/services/tables/services/columns.tsx
- dashboard/src/features/services/tables/users/index.tsx
- dashboard/src/features/services/types/services-mutation.type.ts
- dashboard/src/features/services/types/services.type.ts
- dashboard/src/features/users/components/services-card.tsx
- dashboard/src/features/users/dialogs/mutation/fields/services.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
- dashboard/src/features/users/dialogs/mutation/schema.ts
- dashboard/src/features/users/services/users.query.ts
- dashboard/src/features/users/tables/services/columns.tsx
- dashboard/src/features/users/tables/services/index.tsx
- dashboard/src/features/users/types/index.ts
> refact(api): redesign api models users, services, inbounds relationships

- app/db/crud.py
- app/models/admin.py
- app/routes/admin.py
- app/routes/service.py
- dashboard/src/features/auth/auth.store.ts
- dashboard/src/features/auth/login/form.tsx
- dashboard/src/features/search-command/command-box.tsx
- dashboard/src/features/sidebar/items.tsx
- dashboard/src/features/sidebar/sidebar.tsx
- dashboard/src/features/sudo-routes/index.tsx
- dashboard/src/routes/_dashboard/hosts.lazy.tsx
- dashboard/src/routes/_dashboard/nodes.lazy.tsx
- dashboard/src/routes/_dashboard/services.lazy.tsx
- dashboard/src/routes/_dashboard/settings.lazy.tsx
> feat(role-based-nonsudo-ui): role based UI nonsudo

- dashboard/src/features/users/dialogs/mutation/fields/services.tsx
- dashboard/src/features/users/dialogs/mutation/index.tsx
> improve(users-creation):  show skeleton when loading and alert box when no service is available

- app/dependencies.py
- app/marzneshin.py
- app/routes/admin.py
- app/routes/inbounds.py
- cli/admin.py
- cli/subscription.py
- cli/user.py
- cli/utils.py
- marzneshin-cli.py
Reverts khodedawsh/marzneshin#394
> Revert "refact(backend-lifespan): improving type checking and incorporating lifespan as an alternative to on_event "

- app/dependencies.py
- app/marzneshin.py
- app/routes/admin.py
- app/routes/inbounds.py
- cli/admin.py
- cli/subscription.py
- cli/user.py
- cli/utils.py
- marzneshin-cli.py
This PR aims to resolve few type checking errors and replacing deprecated features of Fast API with new alternative ones.
- Replacing existing ‍`on_event` for graceful shutdown and disposability with [lifespan](https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated).
- Improving type checking and eliminating linting errors
Closes
- #
- #
> refactor: backend

- app/routes/subscription.py
> fix(subscription): cast interval to string

- .github/workflows/package.yml
> ci: fix dashboard version

- app/dependencies.py
- app/routes/admin.py
- app/utils/auth.py
- requirements.txt
> refactor(auth): use pyjwt instead of python-jose

- dashboard/src/features/services/dialogs/mutation/fields/inbounds.tsx
This PR aims to resolve #406 by making sure inbounds are scrollable.
Closes #406
> improve(service-creation): scrollable inbounds

- app/db/migrations/versions/a83e4dd22672_refactor_user_expire.py
fix a migration problem with mariadb
-
-
Closes
- #
- #
> fix(migrations): All MySQL CHANGE/MODIFY COLUMN operations require the existing type

- app/routes/user.py
minor change to fix user updates after editing
-
-
Closes
- #
- #
> fix(user-management): enabling a user by changing data limit

- dashboard/src/features/users/types/schema.ts
round data limit to avoid having a float as the transformed value in bytes
-
-
Closes
- #
- #
> fix: users data limit float

- .github/workflows/package.yml
fix dashboard build in package
-
-
Closes
- #
- #
> ci(package): fix dashboard build

- app/tasks/record_usages.py
Fixes record_user_usages getting stuck 
-
-
Closes
- #
- #
> fix(usage-recording): set a timeout for stats

- app/db/migrations/versions/9001356f0063_create_settings.py
fix the pattern for v2rayng and add streisand
-
-
Closes
- #
- #
> improve(subscription): default subscription rules

- app/utils/share.py
use the default shadowsocks method for now
-
-
Closes
- #
- #
> fix(subscription): use the default shadowsocks method for now

- dashboard/src/features/users/components/tables/users/columns.tsx
- "Enabled" column is removed from users
> improve(users-table): removing enabled column

- dashboard/public/locales/en.json
- dashboard/public/locales/fa.json
- dashboard/public/locales/kur.json
- dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx
- dashboard/src/features/users/components/pills/index.ts
- dashboard/src/features/users/components/pills/user-expired-pill.tsx
Sorting user information and expired indicator
- Sorting user information
- Expired indicator
Closes
- #
- #
> feat(users-settings): expired indicator

- app/marznode/operations.py
Fixes problem with user updates
-
-
Closes
- #
- #
> fix(node-updates): make sure user object is independent to db session

- dashboard/src/features/entity-table/components/sidebar-entity-popover.tsx
- dashboard/src/features/entity-table/sidebar-entity-table.tsx
> fix(entity-table-sidebar): stacking view options and create button on filter for mobile

- dashboard/public/locales/fa.json
updated fa translation according to [#this merge](https://github.com/khodedawsh/marzneshin/pull/430/files#diff-18eb5a4690400122b096fae4b1968fece9f03d296aa3381ce7fceb61f2336d4a)
> improve(translation): persian for admin management

- app/routes/service.py
fixes a mistake in access management for services
-
-
Closes
- #
- #
> fix(access-management): sudo admins have access to services

- app/routes/subscription.py
set subscription headers to 0 when null for better representation in hiddify
> fix(subscription): set subscription headers to 0 when null for better representation in hiddify

- Dockerfile.preview
this Dockerfile combines the building of frontend (dashboard) and serving it along the backend in one image.
this can be useful for previewing PR's and testing the application in the development process.
-
-
Closes
- #
- #
> feat(CI/CD): added a Dockerfile for previewing PR's and testing.

- dashboard/src/features/admins/components/dialogs/mutation/fields/password.tsx
- dashboard/src/features/admins/components/dialogs/mutation/index.tsx
- dashboard/src/features/admins/types/schema.ts
- **feat(admins-creation): password is required and modify users access is by default true**
- **improve(password): password input type specification**
-
-
Closes
- #
- #
> improve(admin-create-schema): admins password input and schema correction

- app/models/proxy.py
- dashboard/src/features/hosts/dialogs/mutation/fields/alpn.tsx
- dashboard/src/features/hosts/schema/hosts-schema.ts
h3 option for host's alpn configuration
- `h3`, `h3,h2`, `h3,h2,http/1.1`, Options in alpn field
Closes #453
- #453
> feat(hosts-alpn): h3 options for alpn

- app/db/crud.py
- app/db/migrations/versions/c4fb5f6423a8_add_hysteria2_protocol_for_inbounds.py
- app/models/proxy.py
- app/utils/share.py
- requirements.txt
Implementing hysteria
- [‌X] My code follows the code style of this project.
> feat(subscription): hysteria

- dashboard/src/components/awaiting/index.tsx
- dashboard/src/features/nodes/dialogs/settings/node-config-editor.tsx
- dashboard/src/features/nodes/dialogs/settings/use-nodes-settings.ts
Await editor config loading while fetching
- **fix(editor-empty-while-fetching): await editor config loading while fetching**
- **refact(awaiting): removing uncessary else clauses**
Closes #471
> fix(editor-empty-while-fetching): await editor config loading while fetching

- README.md
> docs(readme): fix the link to docs

- app/templates/sing-box.json
make sing-box clients work again
> fix(templates): specify some detours correctly in sing-box template

- requirements.txt
update v2share to fix hysteria2 configs not showing up in sing-box
> chore(requirements): update v2share

- dashboard/src/features/entity-table/components/column-header-combo-filter.tsx
Users might not be able to detect whether the table is filterable based on certain options
- Filter icon for filtered columns
> feat(entity-table/filtered-columns): fitler icon to indicate a column is filterable

- app/tasks/record_usages.py
update lifetime_used_traffic correctly
none
Closes
- #551
> fix(record_usages): update lifetime_used_traffic correctly

- requirements.txt
fixes requirements version conflict
> chore(requirements): fix pyopenssl version

- app/db/crud.py
- app/models/system.py
- app/models/user.py
- dashboard/src/common/stats-charts/components/select-date-view.tsx
- dashboard/src/components/widgets/section-widget/index.tsx
- dashboard/src/features/total-traffic-widget/api/total-traffic.query.ts
- dashboard/src/features/total-traffic-widget/index.tsx
- dashboard/src/modules/users/api/queries/user-nodes-usage.query.ts
- dashboard/src/modules/users/components/widgets/user-nodes-usage-widget/index.tsx
feat(stats): add total traffic to get_total_usages return value
"/stats/traffic" response_model
> feat(stats): add total traffic to get_total_usages return value

- app/routes/admin.py
fix: get admin data not found error
> fix(api): return 404 in case admin is not found  

- app/db/crud.py
- app/models/system.py
- app/routes/subscription.py
> feat(subscription): time series user usage data

- app/db/crud.py
- app/routes/service.py
Nullifies username when a user is removed
Closes
- #469
> feat(db): nullify username when removing a user

- requirements.txt
> fix(requirements): add httptools req to fix login problems

- app/db/migrations/versions/b613375d2fca_add_new_protocols_to_proxytypes_enum.py
- app/models/proxy.py
- app/routes/subscription.py
- app/utils/share.py
- requirements.txt
> feat(inbounds): extend proxy types

- dashboard/src/modules/admins/api/admin.query.ts
- dashboard/src/modules/users/api/queries/user.query.ts
- dashboard/src/modules/users/components/dialogs/settings/index.tsx
Resolves the build errors related to query initial data
> fix(users-admins-modules): no initial data required for query options

- app/db/migrations/versions/b613375d2fca_add_new_protocols_to_proxytypes_enum.py
consider mariadb dialect in inbound protocols migration
> fix(migrations): consider mariadb dialect in inbound protocols migration

- app/db/migrations/versions/20241129_a015ed8ce227_add_shadowtls_protocol.py
- app/models/proxy.py
- app/utils/share.py
- dashboard/src/modules/hosts/dialogs/mutation/profiles/shadowtls/default.ts
- dashboard/src/modules/hosts/dialogs/mutation/profiles/shadowtls/index.tsx
- dashboard/src/modules/hosts/dialogs/mutation/profiles/shadowtls/schema.ts
- dashboard/src/modules/hosts/dialogs/mutation/profiles/use-profile-strategy.ts
- dashboard/src/modules/inbounds/types/index.ts
- requirements.txt
> chore(deps): update v2share

- dashboard/src/modules/users/components/dialogs/mutation/sections/data-limit/use-data-limit.ts
> fix(users/data-limit): toggling data limit woudn't make the user unlimited

- dashboard/src/modules/users/components/dialogs/settings/user-info/qrcode.tsx
> fix(users-subscription/qrcode): adding white background to QRCode to be recognized

- app/db/models.py
add user removed check for service userid 
Closes
- #637
> fix(service/userids): add user removed check

- dashboard/src/common/components/header/menu.tsx
- dashboard/src/features/language-switch/index.tsx
- dashboard/src/features/theme-switch/theme-toggle/index.tsx
- dashboard/src/features/version-indicator/index.tsx
- dashboard/src/modules/auth/logout/index.tsx
- dashboard/src/routes/_dashboard.tsx
- **improve(version-indicator): moving the version indicator from footer to menu**
- **improve(version-indicator): removing the marzneshin name from version indicator**
> improve(version-indicator): relocating its location and removing the marzneshin name

- app/db/models.py
Same as #716, but for node usages.
> fix(db): preserve node usages when a node is removed

- app/db/migrations/versions/20240608_9001356f0063_create_settings.py
درود ، خیلی وقته دوستان یه warning الکی و بی اهمیت دریافت میکنن که باعث نگرانی و سوالات تکراری در کامیونیتی میشه، با این pr این مورد فیکس و تموم میشود.
> chore(migrations/patter): fix warning

- app/tasks/record_usages.py
Currently record usages may not work as expected in case node usage coefficient is set to a float value.
> fix(record_usages): cast user usages into int

- dashboard/src/modules/users/domain/schema.ts
allow user data limit to be a float
Closes
- #595
> fix(dashboard): allow user data limit to be float in GB in user mutation

- dashboard/src/modules/hosts/domain/host.ts
fixes port validation error in case of null host port
> fix(hosts): port validation

- dashboard/package.json
- dashboard/src/modules/users/components/dialogs/settings/user-info/table.tsx
Avoids problems with date picker on safari
- in case a datetime value is null, it is now explicitly pointed out.
- [] My code follows the code style of this project.
Closes #545 
- #545
> fix(dashboard): explicitly point out and show never in case a date value is null

- dashboard/src/features/i18n/index.ts
Set html lang attribute based on language change
> improve(i18n): Set html lang attribute based on language change

- dashboard/src/modules/users/components/dialogs/settings/user-info/table.tsx
Fixes user info page problem on safari and other webkit-based browsers.
Closes
- #545
> fix(dashboard): pass correct user dates to fix problems on webkit

- .github/workflows/migration.yml
- app/db/migrations/env.py
- tests/test_migrations.py
Adds tests covering alembic migrations.
> test(migrations): use pytest-alembic for testing the migrations 

- requirements.txt
Fix for https://github.com/marzneshin/marzneshin/pull/112#issuecomment-2661157642
-
-
Closes
- #
- #
> fix(deps): add psycopg-binary for postgresql support

- requirements.txt
https://github.com/khodedawsh/v2share/pull/10#issuecomment-2699061522
> req: v2share

- app/models/user.py
- dashboard/src/modules/users/domain/schema.ts
> fix(users): validate that usage_duration does not exceed 9999 years

- .github/workflows/pr-alerts.yml
با این اکشن، pr هایی که باز میشن نوتیفش به گروه مرزنشین تاپیک توسعه ارسال میشه. فقط کافیه یک TELEGRAM_BOT_TOKEN سکرت تنظیم بشه
> feat(ci-cd): add pr opened alert

- app/models/node.py
- app/models/notification.py
- app/models/proxy.py
- app/models/settings.py
- app/models/user.py
- app/routes/user.py
- cli/subscription.py
بجای str, enum از StrEnum استفاده کردم.
> chore(enum): use StrEnum
