app/dashboard/vite.config.ts
- Remove the cluttering warns while building in dashboard build pipeline job 
- Vite config update: Ignore `Module level directives cause errors when bundled, 'use client'` warn
=> chore: ignore the modules directives warn while building

app/dashboard/index.html, app/dashboard/public/locales/en.json, app/dashboard/src/components/callout/index.tsx, app/dashboard/src/pages/hosts/container.tsx, app/dashboard/src/pages/hosts/dialog/default-values.ts, app/dashboard/src/pages/hosts/dialog/index.tsx, app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx, app/dashboard/src/pages/nodes/dialog.tsx, app/dashboard/src/stores/inbounds.store.ts, makefile
- Auto-Selection of First Inbound: Implemented a feature to automatically select the first inbound at the start if no inbound is selected.
- Refetch Hosts on Creation and Deletion: Modified the logic to refetch hosts once a host is created or deleted. This ensures that the latest data is always displayed on the hosts page.
- Toast Message Consistency: Ensured consistency in the toast message when a host is created. Reused the same message for a cleaner user experience.
- Callout for No Inbounds: Added a callout to notify users when there are no inbounds, providing a clearer indication of the page status.
=> improv(hosts-page): correct refetching, callout, pre-selecting at page startup 

dashboard/src/components/entity-table/entity-table-provider.ts, dashboard/src/components/entity-table/hooks/index.ts, dashboard/src/components/entity-table/hooks/use-dialog.ts, dashboard/src/components/entity-table/hooks/use-entity-query.ts, dashboard/src/components/entity-table/hooks/use-filtering.ts, dashboard/src/components/entity-table/hooks/use-pagination.ts, dashboard/src/components/entity-table/hooks/use-row-selection.ts, dashboard/src/components/entity-table/index.tsx, dashboard/src/components/entity-table/table-filtering.tsx, dashboard/src/components/entity-table/table-pagination.tsx, dashboard/src/components/entity-table/table.tsx, dashboard/src/features/hosts/tables/inbound-hosts/table.tsx, dashboard/src/features/nodes/services/nodes.query.ts, dashboard/src/features/nodes/tables/table.tsx, dashboard/src/features/services/services/services.query.ts, dashboard/src/features/services/tables/services/index.tsx, dashboard/src/features/users/dialogs/mutation/fields/services.tsx, dashboard/src/features/users/services/users.query.ts, dashboard/src/features/users/tables/services/index.tsx, dashboard/src/features/users/tables/users/index.tsx, dashboard/src/routes/_dashboard/users.tsx
Aiming to refactor the entity table for the sake of extend-ability and performance.
- Entity will be using context to pass the table features such as pagination, filtering, etc.
- Moving pagination and sorting process and logic to server from client.
- feat(server-side-entity-table): filtering and table context
- #186
=> feat(server-side-entity-table): server side pagination API for entity table

requirements.txt
fix a problem in vmess urls by updating v2share
=> fix: update v2share to fix incorrect vmess url

app/templates/subscription/index.html
v2ray links should show up when user status is on hold
=> fix: show links also when users are on hold

app/utils/share.py
previously in case a format variable was missing the server would throw an error
=> fix: set a value for missing format variables

dashboard/src/features/users/components/widgets/users-stats-widget/index.tsx, dashboard/src/features/users/components/widgets/users-stats-widget/users-stats-widget.stories.ts
Closes #389
- **docs(users-stats):** total value
- **fix(users-stats):** total value delivered by api instead of calculating it
=> fix(users-stats): total value delivered by api instead of calculating it

app/dependencies.py, app/marzneshin.py, app/routes/admin.py, app/routes/inbounds.py, cli/admin.py, cli/subscription.py, cli/user.py, cli/utils.py, marzneshin-cli.py
This PR aims to resolve few type checking errors and replacing deprecated features of Fast API with new alternative ones.
- Replacing existing ‍`on_event` for graceful shutdown and disposability with [lifespan](https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated).
- Improving type checking and eliminating linting errors
=> refact(backend-lifespan): improving type checking and incorporating lifespan as an alternative to on_event 

dashboard/src/components/page/index.tsx, dashboard/src/features/bottom-menu/index.tsx, dashboard/src/features/sidebar/sidebar.tsx, dashboard/src/features/sidebar/toggle.tsx, dashboard/src/features/version-indicator/index.tsx, dashboard/src/hooks/index.ts, dashboard/src/hooks/use-is-current-route.ts, dashboard/src/routes/_dashboard.tsx
Bottom menu navigation instead of bottom up drawer
- Page sizing is greatly improved
- Bottom menu for mobile navigation (supports sudo-admin, admin)
- Toggle Button
- A new hook for current active route logic
Closes #287
- #287
=> feat(mobile-navgiation): bottom menu for sudo admin and admin

dashboard/src/features/bottom-menu/index.tsx, dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx, dashboard/src/routes/_dashboard.tsx
- Non sudo admins are no longer able to view settings button in mobile view
- Inbound hosts selection in mobile view is now scrollable and does not overflow
- **fix(admin-role): non-sudo admin is not allowed to access settings button**
- Non sudo admins are no longer able to view settings button in mobile view
- **style(inbound-hosts-selection): scrollable inbounds on mobile view**
- Inbound hosts selection in mobile view is now scrollable and does not overflow
=> fix(remove-settings-for-none-sudo): removign settings button on mobile for non-sudo admin

dashboard/src/features/hosts/services/create-host.mutate.ts, dashboard/src/features/hosts/services/delete-host.mutate.ts, dashboard/src/features/hosts/services/update-host.mutate.ts
This PR aims to resolve the issue of not refetching when hosts are updated or created.
=> fix(hosts-inbounds): refetch hosts inbounds

dashboard/src/features/entity-table/components/table-filtering.tsx, dashboard/src/features/entity-table/entity-table.tsx
Resolving entity table filter field responsiveness and other table options for mobile users.
- Entity table filter field and view options are stacked on top of each other to provide more resopnsive experience for mobile user
Closes #435
=> fix(entity-table): stacking view options and create button on filter for mobile

app/routes/subscription.py
expire should be timestamp instead of datetime in subscription headers.
-
-
Closes
- #
- #
=> fix(subscription): fix expire ts in subscription headers to avoid v2box crash

dashboard/src/features/users/types/schema.ts
Resolving editing a user with data limit may result in data
limit cast into bytes issue by reprioritizing metric conversion.
Closes #444
- #444
=> fix(users-data-limit): metric conversion after type conversion

dashboard/src/components/header/menu.tsx, dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/index.tsx, dashboard/src/routes/_dashboard.tsx
Providing admins page access for mobile view
- Including settings and admins page in menu for sudo admins in mobile view
=> feat(header-menu): including settings and admins page in menu for sudo admins in mobile view

dashboard/src/components/sidebar/sidebar-group.tsx, dashboard/src/features/sidebar/sidebar.tsx
- Sidebar group labels are transformed into uppercase to improve visual hierarchy
=> style(dashboard-sidebar): uppercase sidebar group items

app/db/crud.py
Soft deleting users caused user stats to show wrong numbers. This just adds the filter to avoid removed users to be considered in the count.
Closes
- #467
=> fix(stats): filter removed users from the count query

dashboard/src/components/form-fields/date.tsx, dashboard/src/features/users/components/dialogs/mutation/index.tsx
Assigne the default expiration strategy value, so the
schema is valid on the first component mount.
Closes #482
=> fix(users-dialog): assign the default expiration strategy value

dashboard/src/features/entity-table/components/sidebar-entity-popover.tsx, dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
The inbound popover content size is lower so the
user can easily select without scrolling down the entire page.
Closes #480
- #480
=> fix(inbounds-popover): lowering the size of inbounds popover

dashboard/biome.json, dashboard/public/locales/en.json, dashboard/src/components/info-table/date-table-row.tsx, dashboard/src/components/settings-dialog/index.tsx, dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx, dashboard/src/features/users/components/tables/users/columns.tsx
Adding new paramaters and improving the view of existing paramaters in user settings info section.
- Created At info
- Adding time to the online at user info row
- New column for users table which indicates  when the user was online, it shows "No Uses" where the user was never online.
Closes #477 #452 
- #477
- #452
=> feat(users-settings): adding created at and online at with time

dashboard/src/components/settings-dialog/index.tsx
Fixing the vertical undersize of the settings dialog.
=> fix(settings-dialog-scroll): determining the size of screen for smaller vertical size with less bottom gap

dashboard/src/features/sidebar/sidebar.tsx, dashboard/src/features/support-us/card.tsx, dashboard/src/features/support-us/donation-button.tsx, dashboard/src/features/support-us/index.tsx, dashboard/src/features/support-us/popover.tsx, dashboard/src/features/support-us/support-us.stories.tsx, dashboard/src/features/support-us/support-us.test.tsx
Support Us component is simplified and optimized, and also recieves a donation link instead of hard-coded link.
---
- Support Us functionality must be tested within the storybook and manual tested within the marzneshin dashboard.
=> refact(support-us): simplifying component variant logic and component composition

dashboard/src/features/github-repo/github-repo.tsx
Github icon of repo statistics gets oversized for safari browsers both in mobile and desktop versions.
=> fix(github-repo-stats): oversized github logo icon for safari browsers

dashboard/src/features/entity-table/components/column-header-combo-filter.tsx, dashboard/src/features/entity-table/components/table-pagination.tsx, dashboard/src/features/users/services/users.query.ts
Resetting back to page 1 when filters changes
=> improve(entity-table): resetting back to page 1 when filters changes

app/models/user.py
=> fix: Correct JSON schema example to use 'service_ids' instead of 'services'

app/db/crud.py, app/models/user.py
- Set expire_date, usage_duration, and activation_deadline to None when using NEVER expiration strategy.
- Set expire_date to None when using START_ON_FIRST_USE expiration strategy.
- Set usage_duration and activation_deadline are set to None when using FIXED_DATE expiration strategy.
- Ensure that these changes are correctly reflected in the database.
-
-
- 
Closes
- #
- #
=> fix: Update validation for user expiry strategies

app/routes/admin.py, dashboard/public/locales/en.json, dashboard/src/modules/admins/api/disable-admin-users.mutate.ts, dashboard/src/modules/admins/api/enable-admin-users.mutate.ts, dashboard/src/modules/admins/api/index.ts, dashboard/src/modules/admins/components/dialogs/settings/admin-info/table.tsx
Two button to mutate the state of all users of an admin.
- **translate(admins/enable-disable-users): english translation**
- **feat(admins/enable-disable-users): API commands for enable and disable of all users**
- **feat(admins/enable-disable-users): buttons for enable and disable**
- **fix(admins/api): correcting the http methods of enable_users and disable_users**
- HTTP method of the following endpoints have been changed to `POST`
- `GET /api/admins/{username}/disable_users`
- `GET /api/admins/{username}/enable_users`
- The standard HTTP method for requests that change the system state is `POST`.
Closes #568
- #568
=> feat(admins/enable-disable-users): disable and enable all admin's user

app/db/models.py
Stops sqlalchemy from removing node_user_usages when a node is removed
=> fix(db): preserve node user usages when a node is removed

requirements.txt
Fixes subscription output for sing-box, where transport is incorrectly set to tcp + http headers for plain tcp.
=> fix(subscription): update v2share to get tcp transport right

app/routes/node.py
In case the node doesn't respond to the restart request, prevents the endpoint from getting stalled by setting a timeout.
=> fix(nodes): node config modification timeout

.github/workflows/package.yml
explicitly set dashboard version as a variable
=> ci: set vite app version explicitly when building

dashboard/src/libs/entity-table/components/table-pagination.tsx, dashboard/src/libs/entity-table/contexts/entity-table-provider.tsx, dashboard/src/libs/entity-table/double-entity-table.tsx, dashboard/src/libs/entity-table/entity-table.tsx, dashboard/src/libs/entity-table/hooks/use-pagination.ts, dashboard/src/libs/entity-table/hooks/use-sidebar-entity-table.ts, dashboard/src/libs/entity-table/selectable-entity-table.tsx
Entity Table stores the user's choice of row per page in user's browsers and
uses it at a default value for displaying the number of rows to show in table.
Closes #510
- #510
=> feat(entity-table/pagination): storing users row per page pagination
